FORMAT: 1A
HOST: http://giv-sitcomlab.uni-muenster.de:8080

# IPED-Toolkit-API (v3.2)

# Group Hosts
* HOST-OFFICIAL-HTTP ( **MASTER** ): [http://giv-sitcomlab.uni-muenster.de:8080](http://giv-sitcomlab.uni-muenster.de:8080)
* HOST-OFFICIAL-HTTP ( **DEVELOP** ): [http://giv-sitcomlab.uni-muenster.de:8081](http://giv-sitcomlab.uni-muenster.de:8081)
* HOST-OFFICIAL-HTTPS ( **DEVELOP** ): [http://giv-sitcomlab.uni-muenster.de:8444](http://giv-sitcomlab.uni-muenster.de:8444)
* HOST-LOCAL ( DEVELOP ): [http://localhost:8080](http://localhost:8080)

#### Allowed HTTP requests:

| METHODE | Description |
|----------|----------|
| `GET` | Get a resource or list of resources |
| `POST` | To create or update resource |
| `PUT` | To create or update resource |
| `DELETE` | To delete resource |

#### Server Responses:
| CODE | STATUS | Description |
|----------|----------|----------|
|`200`| `OK` | the request was successfull |
|`201`| `CREATED` |  the request was successfull and a resource was created |
|`500`| `INTERNAL SERVER ERROR` | the request is unavailable |


# Group Browser and Videoformats
The application runs only in the 2 Browser below. If you upload videos on the server, please make sure that you upload:

* a `*.mp4`-Format for **Google Chrome** and
* a `*.ogv`-Format for **Mozilla Firefox**.

Please upload both formats everytime for a better browsersupport and make sure that the **filenames are still the same**!

**ATTENTION IF YOU USE THE REQUESTS:**

* `[POST] /api/videos` or 
* `[PUT] /api/videos/:id` 

and you want to submit a server-path, of the uploaded files, for example **task08.mp4** and **task08.ogv**,<br/>
**DO NEVER SUBMIT THE DATATYPE** `*.mp4` **OR** `*.ogv` **WITH YOUR URL!**<br/>
**YOUR URL SHOULD ONLY CONENTS THE FILENAME, for example:** `http://giv-sitcomlab.uni-muenster.de:8080/media/video/task08`.<br/>
The application will check the browser and will pick the right videoformat automatically, so you don't need to submit them, thank you!


# Group For developers 

>**Note**: only for the API-Specification on Apiary.io

#### API-Example of the blueprint code:
* for API-Syntax check out the **Apiary-Tutorial**: [http://apiary.io/blueprint](http://apiary.io/blueprint)
* for API-Syntax check out the **Blueprint-Documenation**: [http://apiblueprint.org](http://apiblueprint.org)
* for a good example of the API-Syntax check out the **GoodData API** ([http://docs.gooddata.apiary.io](http://docs.gooddata.apiary.io)) with the corresponding Markdownfile *apiary.apib* in the GitHub-Respository ([https://github.com/gooddata/gooddata-api-docs.git](https://github.com/gooddata/gooddata-api-docs.git)).

#### API-Comments:
It is possible to write a comments to discuss the API-Specification on Apiary. Leave the EDITOR-MODE and go to DOCUMENTATION. Scroll down to the corresponding function and click the 
**Add comment**-Button on the right side of the box.


# Group Locations

## Locations Collection [/api/locations]
### List all Locations [GET]

+ Response 200 (application/json)

        [
            {
                "tags":[
                    "Münster",
                    "Frauenstraße",
                    "ULB",
                    "Küpers",
                    "Überwasserkirche",
                    "Meyer-Potthof"
                ],
                "lon":7.6208476,
                "description":"Blick Richtung ULB",
                "name":"Frauenstraße 2",
                "lat":51.9633794,
                "id":701,
                "relatedLocations":[
                    710,
                    702
                ],
                "videos":[
                    713
                ],
                "overlays":[]
            },
            {
                "tags":[
                    "Münster",
                    "Krummer Timpen",
                    "ULB",
                    "Juridicum"
                ],
                "lon":7.6201791,
                "description":"Gegenüber der ULB",
                "name":"Krummer Timpen",
                "lat":51.9627494,
                "id":702,
                "videos":[
                    714
                ],
                "relatedLocations":[
                    699,
                    703,
                    701
                ],
                "overlays":[]
            },
            {
                "tags":[
                    "Juridicum",
                    "Krummer Timpen",
                    "ULB",
                    "Münster"
                ],
                "lon":"7.619770",
                "description":"",
                "name":"Krummer Timpen 2",
                "lat":"51.962613",
                "id":703,
                "overlays":[],
                "videos":[
                    715
                ],
                "relatedLocations":[
                    704,
                    702
                ]
            }
        ] 

+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage>


### Create a Location [POST]

<u>**Required properties**</u>:

| Property | Datatype | Can be empty | Condition | Options | Example |
|----------|----------|----------|----------|----------|----------|
| `name` | <b>String</b> | no | | | `"Frauenstraße"` |
| `description` | <b>String</b> | yes | | "" | `"Gegenüber der Trattoria"` |
| `tags[ ]` | <b>String [ ]</b> | yes | - unique items <br> - item can not be "" | `[]` | `["Münster",` <br> `"Frauenstraße",` <br> `"Trattoria",` <br> `"Kulturcafé"` <br> `"Fürstin-von-Gallitzin-Wohnheim"]` |
| `lon` | <b>Number</b> | no | | *""* | `7.6189278` |
| `lat` | <b>Number [ ]</b> | no | | | `51.9634288` |
| `relatedLocations[ ]` | <b>Integer [ ]</b> | no | valid Location-IDs | `[]` | `[1,6,9,4,5]` |
| `videos[ ]` | <b>Integer [ ]</b> | no | valid video-IDs | `[]` | `[3]` |
| `overlays[ ]` | <b>Integer [ ]</b> | no | valid overlay-IDs | `[]` | `[2,7,8]` |


+ Request (application/json)

    + Body
    
                { 
                    "name": "Frauenstraße", 
                    "tags": [
                        "Münster",
                        "Frauenstraße",
                        "Trattoria",
                        "Kulturcafé",
                        "Fürstin-von-Gallitzin-Wohnheim"
                    ],
                    "lon": 7.6189278,
                    "lat": 51.9634288,
                    "description": "Gegenüber der Trattoria",
                    "relatedLocations": [],
                    "videos": [],
                    "overlays": []
                }

+ Response 201 (application/json)

        {
            "id":4,
            "name":"Frauenstraße",
            "tags":[
                "Münster",
                "Frauenstraße",
                "Trattoria",
                "Kulturcafé",
                "Fürstin-von-Gallitzin-Wohnheim"
            ],
            "lon": 7.6189278,
            "lat": 51.9634288,
            "description":"Gegenüber der Trattoria",
            "relatedLocations": [],
            "videos": [],
            "overlays": []
        }

+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage>

## Location [/api/locations/{id}]
A single Location object with all its details

+ Parameters
    + id (required, Interger, `4`) ... `id` of a **Location**

### Retrieve a Location [GET]

+ Response 200 (application/json)

    + Body
    
            {
                "id":4,
                "name":"Frauenstraße",
                "tags":[
                    "Münster",
                    "Frauenstraße",
                    "Trattoria",
                    "Kulturcafé",
                    "Fürstin-von-Gallitzin-Wohnheim"
                ],
                "lon":7.6189278,
                "lat":51.9634288,
                "description":"Gegenüber der Trattoria",
                "relatedLocations": [
                    1, 
                    3
                ],
                "videos": [
                    5
                ]
                "overlays": [
                    7,
                    8
                ]
            }
            
+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage>

### Edit a Location [PUT]

<u>**Changeable properties**</u>:

| Property | Datatype | Can be empty | Condition | Options | Example |
|----------|----------|----------|----------|----------|----------|
| `name` | <b>String</b> | no | | | `"Frauenstraße"` |
| `description` | <b>String</b> | yes | | "" | `"Gegenüber der Trattoria"` |
| `tags[ ]` | <b>String [ ]</b> | yes | - unique items <br> - item can not be "" | `[]` | `["Münster",` <br> `"Frauenstraße",` <br> `"Trattoria",` <br> `"Kulturcafé"` <br> `"Fürstin-von-Gallitzin-Wohnheim"]` |
| `lon` | <b>Number</b> | no | | *""* | `7.6189278` |
| `lat` | <b>Number [ ]</b> | no | | | `51.9634288` |
| `relatedLocations[ ]` | <b>Integer [ ]</b> | no | valid Location-IDs | `[]` | `[1,6,9,4,5]` |
| `videos[ ]` | <b>Integer [ ]</b> | no | valid video-IDs | `[]` | `[3]` |
| `overlays[ ]` | <b>Integer [ ]</b> | no | valid overlay-IDs | `[]` | `[2,7,8]` |

<u>**Optional properties**</u> (not neccessary, but acceptable):

| Property | Datatype | Can be empty | Condition | Options | Example |
|----------|----------|----------|----------|----------|----------|
| `id` | <b>Integer</b> | no | not changebale | | `4` |


+ Request (application/json)

    + Body
    
            {
                "name":"Frauenstraße 2",
                "tags":[
                    "Münster",
                    "Frauenstraße",
                    "Trattoria",
                    "Kulturcafé",
                    "Fürstin-von-Gallitzin-Wohnheim"
                ]
            }

+ Response 201 (application/json)

        {
                "id":4,
                "name":"Frauenstraße 2",
                "tags":[
                    "Münster",
                    "Frauenstraße",
                    "Trattoria",
                    "Kulturcafé",
                    "Fürstin-von-Gallitzin-Wohnheim"
                ],
                "lon":7.6189278,
                "lat":51.9634288,
                "description":"Gegenüber der Trattoria",
                "relatedLocations": [],
                "videos": [
                    711
                ],
                "overlays": []
        }
        
+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage>

### Remove a Location [DELETE]

+ Response 204

+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage>

## Relations of a Location [/api/locations/{id}/locations]

+ Parameters
    + id (required, Interger, `699`) ... `id` of a **Location**

### Retrieve all related Locations of a Location [GET]

+ Response 200

    + Body
    
            [
                {
                    "tags": [
                        "Münster",
                        "Frauenstraße",
                        "Trattoria",
                        "Kulturcafé",
                        "Fürstin-von-Gallitzin-Wohnheim"
                    ],
                    "lon": "7.6189278",
                    "description": "Gegenüber der Trattoria",
                    "name": "Frauenstraße",
                    "lat": "51.9634288",
                    "id": 710
                },
                {
                    "tags": [
                        "Münster",
                        "Krummer Timpen",
                        "ULB",
                        "Juridicum"
                    ],
                    "lon": 7.6201791,
                    "description": "Gegenüber der ULB",
                    "name": "Krummer Timpen",
                    "lat": 51.9627494,
                    "id": 702
                }
            ]

+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage>


# Group Videos

## Videos Collection [/api/videos]

### List all Videos [GET]

+ Response 200 (application/json)

        [
            {
                "id": 35,
                "description": "Frauenstraße bei Tag",
                "name": "Frauenstraße",
                "date": "",
                "url": "/media/video/task_02",
                "tags": []
            },
            {
                "id": 36,
                "description": "Frauenstraße bei Tag",
                "name": "Frauenstraße2",
                "date": "",
                "url": "/media/video/task_03",
                "tags": []
            }
        ]
        
+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage>     

### Create a Video [POST]

<u>**Required properties**</u>:

| Property | Datatype | Can be empty | Condition | Options | Example |
|----------|----------|----------|----------|----------|----------|
| `name` | <b>String</b> | no | | | `"Frauenstraße"` |
| `description` | <b>String</b> | yes | | "" | `"Frauenstraße bei Tag"` |
| `tags[]` | <b>String [ ]</b> | yes | - unique items <br> - item can not be "" | `[]` | `["Münster", "Frauenstraße", "Bei Tag"]`|
| `date` | <b>String</b> | yes | - has to be the form: **YYYY-MM-DD** / **YYYY-MM-DD HH:mm** <br> - **Y**=Year <br> - **M**=Month <br> - **D**=Day <br> - **H**=Hour <br> - **m**=Minute | *""* | `"2014-06-22"` \ `"2014-06-22 08:03"` |
| `url` | <b>String</b> | no | - valid URL <br> - URL has to be without datatype at the end | | `/media/video/task_03` |

<u>**ATTENTION**</u>: <br>
- The URL of the video does not contain the datatype at the end:
- `/media/video/task_03.mp4` is wrong
- `/media/video/task_03` is correct
- If your videos are located on the same server, please reach them by the shorter URL `/media/video/task_03` instead of the global URL `http://giv-sitcomlab.uni-muenster.de:8080/media/video/task_03` **to provide CROSS-ORIGIN-issues** in your Browser
- Please have a look on the [Browser and Videoformats](#browser-and-videoformats) on the top of this document.


+ Request (application/json)

    + body
    
            { 
                "description": "Frauenstraße bei Tag",
                "name": "Frauenstraße2",
                "date": "",
                "url": "/media/video/task_03",
                "tags":[]
            }

+ Response 201 (application/json)

        {  
            "id":36,
            "description":"Frauenstraße bei Tag",
            "name":"Frauenstraße2",
            "date":"",
            "url":"/media/video/task_03",
            "tags":[]
        }
        
+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage>

## Video [/api/videos/{id}]
A single Video object with all details

+ Parameters
   + id (required, Interger, `36`) ... `id` of a **Video**

### Retrieve a video [GET]

+ Response 200 (application/json)

    + Body

            {  
                "id":36,
                "description":"Frauenstraße bei Tag",
                "name":"Frauenstraße2",
                "date":"",
                "url":"/media/video/task_03",
                "tags":[]
            }
            
+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage>

### Edit a Video [PUT]

<u>**Changeable properties**</u>:

| Property | Datatype | Can be empty | Condition | Options | Example |
|----------|----------|----------|----------|----------|----------|
| `name` | <b>String</b> | no | | | `"Frauenstraße"` |
| `description` | <b>String</b> | yes | | "" | `"Frauenstraße bei Tag"` |
| `tags[]` | <b>String [ ]</b> | yes | - unique items <br> - item can not be "" | `[]` | `["Münster", "Frauenstraße", "Bei Tag", <br> "Kulturcafé", "Fürstin-von-Gallitzin-Wohnheim"]` |
| `date` | <b>String</b> | yes | - has to be the form: **YYYY-MM-DD** / **YYYY-MM-DD HH:mm** <br> - **Y**=Year <br> - **M**=Month <br> - **D**=Day <br> - **H**=Hour <br> - **m**=Minute | *""* | `"2014-06-22"` \ `"2014-06-22 08:03"` |
| `url` | <b>String</b> | no | - valid URL <br> - URL has to be without datatype at the end | | `/media/video/task_03` |

<u>**Optional properties**</u> (not neccessary, but acceptable):

| Property | Datatype | Can be empty | Condition | Options | Example |
|----------|----------|----------|----------|----------|----------|
| `id` | <b>Integer</b> | no | | | `36` |

<u>**ATTENTION**</u>:<br>
- The URL of the video does not contain the datatype at the end:
- `/media/video/task_03.mp4` is wrong
- `/media/video/task_03` is correct
- If your videos are located on the same server, please reach them by the shorter URL `/media/video/task_03` instead of the global URL `http://giv-sitcomlab.uni-muenster.de:8080/media/video/task_03` **to provide CROSS-ORIGIN-issues** in your Browser
- Please have a look on the [Browser and Videoformats](#browser-and-videoformats) on the top of this document.




+ Request (application/json)

    + body
    
                { 
                    "description": "Frauenstraße bei Nacht",
                    "name": "Frauenstraße 2"
                }

+ Response 201 (application/json)

        {  
            "id":36,
            "description":"Frauenstraße bei Nacht",
            "name":"Frauenstraße 2",
            "date":"",
            "url":"/media/video/task_03",
            "tags":[]
        }
        
+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage>

### Remove a Video [DELETE]

+ Response 204

+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage>

## Relations of a Location [/api/locations/{id}/videos]

+ Parameters
    + id (required, Interger, `699`) ... `id` of a **Location**

### Retrieve all Videos of a Location [GET]

+ Response 200

    + Body
    
            [
                {
                    "tags": [
                        "Schlossplatz",
                        "bei Tag"
                    ],
                    "description": "Schlossplatz bei Tag",
                    "name": "Schlossplatz",
                    "date": "No date available",
                    "url": "/media/video/task_01",
                    "id": 711
                }
            ]

+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage>

# Group Overlays

## Overlays Collection [/api/overlays]
### List all Overlays [GET]

+ Response 200 (application/json)
        
        [
            {
                "id": 59,
                "name": "Nachrichten",
                "description": "Uni Muenster Homepage",
                "tags": [
                    "Webpage", 
                    "WWU", 
                    "News"
                ],
                "type": "html",
                "url": "http://www.uni-muenster.de/de/",
                "w": 700,
                "h": 575,
                "x": 547.6430973457741,
                "y": 323.2137010950475,
                "z": -228.65846681625413,
                "d": 1,
                "rx": 0,
                "ry": 0,
                "rz": 0,
                "sx": 1,
                "sy": 1,
                "sz": 1
            }
        ]
        
+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage>

### Create an Overlay [POST]

<u>**Required properties**</u>:

| Property | Datatype | Can be empty | Condition | Options | Example |
|----------|----------|----------|----------|----------|----------|
| `name` | <b>String</b> | no | | | `"Nachrichten"` |
| `description` | <b>String</b> | yes | | *""* | `"Uni Muenster Homepage"` |
| `tags[]` | <b>String [ ]</b> | yes | - unique items <br> - item can not be *""* | `[]` | `["Webpage", "WWU", "News"]` |
| `type` | <b>String</b> | no | | - *"html"* <br> - *"image"* <br> - *"video"* | `"html"` |
| `url` | <b>String</b> | no | - valid URL <br> | | `http://www.uni-muenster.de/de/` |
| `w` | <b>Number</b> | no | | | `700` |
| `h` | <b>Number</b> | no | | | `500` |
| `x` | <b>Number</b> | no | | | `0` |
| `y` | <b>Number</b> | no | | | `0` |
| `z` | <b>Number</b> | no | | | `0` |
| `d` | <b>Number</b> | no | | | `1` |
| `rx` | <b>Number</b> | no | | | `0` |
| `ry` | <b>Number</b> | no | | | `0` |
| `rz` | <b>Number</b> | no | | | `0` |
| `sx` | <b>Number</b> | no | | | `1` |
| `sy` | <b>Number</b> | no | | | `1` |
| `sz` | <b>Number</b> | no | | | `1` |

+ Request (application/json)

    + body 
    
            {
                "name": "Nachrichten",
                "description": "Uni Muenster Homepage",
                "tags": [
                    "Webpage", 
                    "WWU", 
                    "News"
                ],
                "type": "html",
                "url": "http://www.uni-muenster.de/de/",
                "w": 700,
                "h": 575,
                "x": 547.6430973457741,
                "y": 323.2137010950475,
                "z": -228.65846681625413,
                "d": 1,
                "rx": 0,
                "ry": 0,
                "rz": 0,
                "sx": 1,
                "sy": 1,
                "sz": 1
            }

+ Response 201 (application/json)

            {
                "id": 59,
                "name": "Nachrichten",
                "description": "Uni Muenster Homepage",
                "tags": [
                    "Webpage", 
                    "WWU", 
                    "News"
                ],
                "type": "html",
                "url": "http://www.uni-muenster.de/de/",
                "w": 700,
                "h": 575,
                "x": 547.6430973457741,
                "y": 323.2137010950475,
                "z": -228.65846681625413,
                "d": 1,
                "rx": 0,
                "ry": 0,
                "rz": 0,
                "sx": 1,
                "sy": 1,
                "sz": 1
            }

+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage>

## Overlay [/api/overlays/{id}]
A single Overlay object with all its details

+ Parameters
   + id (required, Interger, `59`) ... `id` of an **Overlay**

### Retrieve an Overlay [GET]

+ Response 200 (application/json)

    + Body

            {
                "id": 59,
                "name": "Nachrichten",
                "description": "Uni Muenster Homepage",
                "tags": [
                    "Webpage", 
                    "WWU", 
                    "News"
                ],
                "type": "html",
                "url": "http://www.uni-muenster.de/de/",
                "w": 700,
                "h": 575,
                "x": 547.6430973457741,
                "y": 323.2137010950475,
                "z": -228.65846681625413,
                "d": 1,
                "rx": 0,
                "ry": 0,
                "rz": 0,
                "sx": 1,
                "sy": 1,
                "sz": 1
            }
            
+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage>            

### Edit an Overlay [PUT]

<u>**Changeable properties**</u>:

| Property | Datatype | Can be empty | Condition | Options | Example |
|----------|----------|----------|----------|----------|----------|
| `name` | <b>String</b> | no | | | `"Nachrichten"` |
| `description` | <b>String</b> | yes | | *""* | `"Uni Muenster Homepage"` |
| `tags[]` | <b>String [ ]</b> | yes | - unique items <br> - item can not be *""* | `[]` | `["Webpage", "WWU", "News"]` |
| `type` | <b>String</b> | no | | - *"html"* <br> - *"image"* <br> - *"video"* | `"html"` |
| `url` | <b>String</b> | no | - valid URL <br> | | `http://www.uni-muenster.de/de/` |
| `w` | <b>Number</b> | no | | | `700` |
| `h` | <b>Number</b> | no | | | `500` |
| `x` | <b>Number</b> | no | | | `0` |
| `y` | <b>Number</b> | no | | | `0` |
| `z` | <b>Number</b> | no | | | `0` |
| `d` | <b>Number</b> | no | | | `1` |
| `rx` | <b>Number</b> | no | | | `0` |
| `ry` | <b>Number</b> | no | | | `0` |
| `rz` | <b>Number</b> | no | | | `0` |
| `sx` | <b>Number</b> | no | | | `1` |
| `sy` | <b>Number</b> | no | | | `1` |
| `sz` | <b>Number</b> | no | | | `1` |

<u>**Optional properties**</u> (not neccessary, but acceptable):

| Property | Datatype | Can be empty | Condition | Options | Example |
|----------|----------|----------|----------|----------|----------|
| `id` | <b>Integer</b> | no | | | `59` |

+ Request (application/json)

    + body 
    
            {
                "id": 59,
                "name": "Nachrichten",
                "description": "Uni Muenster Homepage",
                "tags": [
                    "Webpage", 
                    "WWU", 
                    "News"
                ],
                "type": "html",
                "url": "http://www.uni-muenster.de/de/",
                "w": 700,
                "h": 575,
                "x": 547.6430973457741,
                "y": 323.2137010950475,
                "z": -228.65846681625413,
                "d": 1,
                "rx": 0,
                "ry": 0,
                "rz": 0,
                "sx": 1,
                "sy": 1,
                "sz": 1
            }

+ Response 201 (application/json)

        {
                "id": 59,
                "name": "Nachrichten",
                "description": "Uni Muenster Homepage",
                "tags": [
                    "Webpage", 
                    "WWU", 
                    "News"
                ],
                "type": "html",
                "url": "http://www.uni-muenster.de/de/",
                "w": 700,
                "h": 575,
                "x": 547.6430973457741,
                "y": 323.2137010950475,
                "z": -228.65846681625413,
                "d": 1,
                "rx": 0,
                "ry": 0,
                "rz": 0,
                "sx": 1,
                "sy": 1,
                "sz": 1
            }
        
+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage>


### Remove an Overlay [DELETE]

+ Response 204

+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage>

## Relations of a Location [/api/locations/{id}/overlays]

+ Parameters
    + id (required, Interger, `699`) ... `id` of a **Location**

### Retrieve all Overlays of a Location [GET]

+ Response 200

    + Body
    
            [
                {
                    "id": 59,
                    "name": "Nachrichten",
                    "description": "Uni Muenster Homepage",
                    "tags": [
                        "Webpage", 
                        "WWU", 
                        "News"
                    ],
                    "type": "html",
                    "url": "http://www.uni-muenster.de/de/",
                    "w": 700,
                    "h": 575,
                    "x": 547.6430973457741,
                    "y": 323.2137010950475,
                    "z": -228.65846681625413,
                    "d": 1,
                    "rx": 0,
                    "ry": 0,
                    "rz": 0,
                    "sx": 1,
                    "sy": 1,
                    "sz": 1
                }
            ]

+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage>
        
# Group Relationship-Weighting

## Relationship [/api/relationships/{id}]

+ Parameters
    + id (required, Interger, `19`) ... `id` of a **Relationship**

### Get a Relationship [GET]

+ Response 200 (application/json)

        {
            "id": 19,
            "intents": []
        }
  
+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage> 

### Edit a Relationship [PUT]

<u>**Changeable properties**</u>:

| Property | Datatype | Can be empty | Condition | Options | Example |
|----------|----------|----------|----------|----------|----------|
| `intents[ ]` | <b>String [ ]</b> | yes | - unique items <br> - item can not be *""* | `[]` | `[]` |

<u>**Optional properties**</u> (not neccessary, but acceptable):

| Property | Datatype | Can be empty | Condition | Options | Example |
|----------|----------|----------|----------|----------|----------|
| `id` | <b>Integer</b> | no | | | `18` |


+ Request (application/json)

    + Body
        
            {
                "intents": []
            }

+ Response 200 (application/json)

        {
            "id": 19,
            "intents": []
        }
  
+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage> 

### Delete a Relationship [DELETE]

+ Response 204 (application/json)
  
+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage> 

## Relationship weighting between 2 Locations [/api/locations/{id_start}/locations/{id_end}]

+ Parameters
    + id_start (required, Interger, `18`) ... `id` of a **Location**
    + id_end (required, Interger, `23`) ... `id` of a **Location**

### Get a Relationship [GET]
    
+ Response 200 (application/json)

        {
            "id": 19,
            "intents": []
        }
  
+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage> 

### Create a Relationship [POST]

<u>**Required properties**</u>:

| Property | Datatype | Can be empty | Condition | Options | Example |
|----------|----------|----------|----------|----------|----------|
| `intents[ ]` | <b>String [ ]</b> | yes | - unique items <br> - item can not be *""* | `[]` | `[]` |


+ Request (application/json)

    + Body
        
            {
                "intents": []
            }
    
+ Response 200 (application/json)

        {
            "id": 19,
            "intents": []
        }
  
+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage> 
        
### Edit a Relationship [PUT]

<u>**Changeable properties**</u>:

| Property | Datatype | Can be empty | Condition | Options | Example |
|----------|----------|----------|----------|----------|----------|
| `intents[ ]` | <b>String [ ]</b> | yes | - unique items <br> - item can not be *""* | `[]` | `[]` |

<u>**Optional properties**</u> (not neccessary, but acceptable):

| Property | Datatype | Can be empty | Condition | Options | Example |
|----------|----------|----------|----------|----------|----------|
| `id` | <b>Integer</b> | no | | | `18` |


+ Request (application/json)

    + Body
        
            {
                "id": 19,
                "intents": []
            }
    
+ Response 200 (application/json)

        {
            "id": 19,
            "intents": []
        }
  
+ Response 500 (text/plain)

        Error: Internal Server Error
        Message: <Errormessage> 
